name: survival-kit-local

services:
  postgres:
    image: postgres:16
    container_name: survival-kit-local-database
    env_file:
      - ../.env
    environment:
      POSTGRES_DB: ${POSTGRES_NAME:-survival-kit}
      POSTGRES_USER: ${POSTGRES_USER:-survival-kit}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-survival-kit}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailhog:
    image: mailhog/mailhog
    container_name: survival-kit-local-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"   # Web UI to view emails

  redis:
    image: redis:7-alpine
    container_name: survival-kit-local-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    env_file:
      - ../.env
    command: sh -c "redis-server --appendonly yes --requirepass $$REDIS_PASSWORD"
    restart: unless-stopped

volumes:
  postgres_data:
    name: survival-kit_local_postgres
  redis_data: