spring.application.name=backend

# Hibernate is disabled because Flyway will manage schema
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

spring.flyway.schemas=public
spring.flyway.default-schema=public

spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML

spring.threads.virtual.enabled=true