spring.application.name=backend

# Hibernate is disabled because Flyway will manage schema
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=false

logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.autoconfigure.flyway=DEBUG

spring.flyway.schemas=public
spring.flyway.default-schema=public

spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML

spring.threads.virtual.enabled=true