spring.datasource.url=jdbc:postgresql://localhost:5432/survival-kit
spring.datasource.username=survival-kit
spring.datasource.password=survival-kit
spring.datasource.driver-class-name=org.postgresql.Driver