spring.config.import=optional:file:.env-local[.properties]

spring.datasource.url=jdbc:postgresql://localhost:5432/survival-kit
spring.datasource.username=survival-kit
spring.datasource.password=survival-kit
spring.datasource.driver-class-name=org.postgresql.Driver

#logging.level.org.springframework.boot=DEBUG
logging.level.org.flywaydb=DEBUG

app.jwt.secret=aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
app.jwt.expiration-ms=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.org.springframework.boot.context.config=TRACE
