spring.config.import=optional:file:../.env-local[.properties]

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration

#logging.level.org.springframework.boot=DEBUG
logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.context.config=TRACE

#jwt
app.jwt.secret=very_long_random_secret-g7656ithre3636th-rth-rth6rtzh-rthrtzrtzh-trznhr6h
app.jwt.expiration-ms=86400000

#mail
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=mail_username
spring.mail.password=mail_password
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false