spring.config.import=optional:file:../.env-local[.properties]

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration

#logging.level.org.springframework.boot=DEBUG
logging.level.org.flywaydb=DEBUG
logging.level.org.springframework.boot.context.config=TRACE

#jwt
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=${JWT_EXPIRATION}

#mail
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false